// <auto-generated />
using System;
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataModel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataModel.ImageRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("Action");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("AssetId");

                    b.Property<long>("CompressedSize")
                        .HasColumnType("BIGINT")
                        .HasColumnName("CompressedSize");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedTime");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("LastUpdatedTime");

                    b.Property<string>("MD5Hash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("MD5Hash");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("OriginalPath");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("BIGINT")
                        .HasColumnName("OriginalSize");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("OutputPath");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("TaskId");

                    b.Property<int>("UploadedToApi")
                        .HasColumnType("int")
                        .HasColumnName("UploadedToApi");

                    b.HasKey("ID");

                    b.ToTable("ImageRecord");
                });

            modelBuilder.Entity("DataModel.LogEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("Action");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedTime");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("LastUpdatedTime");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Source");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("ID");

                    b.ToTable("LogEntity");
                });

            modelBuilder.Entity("DataModel.ProcessingTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("Action");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int")
                        .HasColumnName("CompletedCount");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedTime");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("LastUpdatedTime");

                    b.Property<string>("OutputFolder")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("OutputFolder");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("SourceFolder");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int")
                        .HasColumnName("TotalCount");

                    b.HasKey("ID");

                    b.ToTable("ProcessingTask");
                });
#pragma warning restore 612, 618
        }
    }
}
